CREATE TABLE "PUBLIC"."PAYMENTADDRESS"
(
   ID varchar(255),
   USERNAME varchar(255)
)
;
CREATE TABLE "PUBLIC"."PREMIUMPAYMENTS"
(
   ID varchar(255),
   USERNAME varchar(255),
   PAYTIME integer,
   PAYAMOUNT integer,
   PAYMENTADDRESS varchar(255)
)
;
CREATE TABLE "PUBLIC"."TEAM"
(
   ID varchar(255) PRIMARY KEY NOT NULL,
   TOKEN varchar(255),
   NAME varchar(255)
)
;
CREATE UNIQUE INDEX PRIMARY_KEY_27 ON "PUBLIC"."TEAM"(ID)
;
CREATE TABLE "PUBLIC"."TEAMMEMBERSHIP"
(
   TEAM varchar(255) NOT NULL,
   USER varchar(255) NOT NULL,
   CONSTRAINT PK_TEAMMEMBERSHIP PRIMARY KEY (TEAM,USER)
)
;
CREATE UNIQUE INDEX PRIMARY_KEY_F ON "PUBLIC"."TEAMMEMBERSHIP"
(
  TEAM,
  USER
)
;
CREATE TABLE "PUBLIC"."TOKEN"
(
   NAME varchar(128) NOT NULL,
   ID varchar(255) PRIMARY KEY NOT NULL,
   CLAIMEDBY varchar(255),
   CLAIMTIME bigint,
   PICURL varchar(255)
)
;
CREATE UNIQUE INDEX PRIMARY_KEY_9 ON "PUBLIC"."TOKEN"(ID)
;
CREATE TABLE "PUBLIC"."TOKENAPPLICANT"
(
   ID varchar(255),
   TOKENID varchar(255),
   ENQUEUETIME bigint,
   APPLICANTNAME varchar(255)
)
;
CREATE TABLE "PUBLIC"."TOKENUSERREFERENCE"
(
   ID varchar(255),
   TOKENID varchar(255),
   USERNAME varchar(255)
)
;
CREATE TABLE "PUBLIC"."USER"
(
   ID varchar(255) PRIMARY KEY NOT NULL,
   FIRSTNAME varchar(255),
   LASTNAME varchar(255)
)
;
CREATE UNIQUE INDEX PRIMARY_KEY_2 ON "PUBLIC"."USER"(ID)
;
