# --- !Ups


CREATE TABLE "PUBLIC"."PAYMENTADDRESS"
(
   ID varchar(255),
   USERNAME varchar(255)
)
;
CREATE TABLE "PUBLIC"."PREMIUMPAYMENTS"
(
   ID varchar(255),
   USERNAME varchar(255),
   PAYTIME integer,
   PAYAMOUNT integer,
   PAYMENTADDRESS varchar(255)
)
;
CREATE TABLE "PUBLIC"."TEAM"
(
   ID varchar(255) PRIMARY KEY NOT NULL,
   TOKEN varchar(255),
   NAME varchar(255)
)
;
CREATE TABLE "PUBLIC"."TEAMMEMBERSHIP"
(
   TEAM varchar(255) NOT NULL,
   USER varchar(255) NOT NULL,
   CONSTRAINT PK_TEAMMEMBERSHIP PRIMARY KEY (TEAM,USER)
)
;
CREATE TABLE "PUBLIC"."TOKEN"
(
   NAME varchar(128) NOT NULL,
   ID varchar(255) PRIMARY KEY NOT NULL,
   CLAIMEDBY varchar(255),
   CLAIMTIME bigint,
   PICURL varchar(255)
)
;

CREATE TABLE "PUBLIC"."TOKENAPPLICANT"
(
   ID varchar(255),
   TOKENID varchar(255),
   ENQUEUETIME bigint,
   APPLICANTNAME varchar(255)
)
;
CREATE TABLE "PUBLIC"."TOKENUSERREFERENCE"
(
   ID varchar(255),
   TOKENID varchar(255),
   USERNAME varchar(255)
)
;
CREATE TABLE "PUBLIC"."USER"
(
   ID varchar(255) PRIMARY KEY NOT NULL,
   FIRSTNAME varchar(255),
   LASTNAME varchar(255)
)
;

# --- !Downs
DROP TABLE "PUBLIC"."USER";
DROP TABLE "PUBLIC"."TOKENUSERREFERENCE";
DROP TABLE "PUBLIC"."TOKENAPPLICANT";
DROP TABLE "PUBLIC"."TEAMMEMBERSHIP";
DROP TABLE "PUBLIC"."TEAM";
DROP TABLE "PUBLIC"."PREMIUMPAYMENTS";
DROP TABLE "PUBLIC"."PAYMENTADDRESS";